Upgrade `fs-extra` (#431)
* Upgrade `fs-extra`

* Change the value of _codeDirectory

I got the following error.
```
Error: Cannot copy '.' to a subdirectory of itself, 'DIR/node-lambda/.lambda'.
```

* Fix to use relative path when copying files

It seems that `src` of the filter function has changed to relative path.