Drop old Node support  (#523)
* Upgrade packages

There was a major upgrade in some packages.

* Drop Node.js 8.x from workflow.yml

```
/home/runner/work/node-lambda/node-lambda/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
```

* Drop old Node support

Depends on 'fs-extra'.
https://github.com/jprichardson/node-fs-extra/pull/751