Upgrade packages
It is an error due to the upgrade of 'commander'.

```
Error: option 'description' clashes with existing property 'description' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name
```

Fixed it.